Check if xhost command is available in expose-xhost target (not available e.g. on raspberry pi by default)

diff --git a/docker/Makefile b/docker/Makefile
--- a/docker/Makefile
+++ b/docker/Makefile
@@ -172,12 +172,17 @@ GUI_SERVICES = px4 ardupilot qgc rviz qgis gisnav fileserver
 
 # Expose xhost to containers that need GUI (see x11 extension in docker-compose.yaml)
 expose-xhost:
-	@for containerId in `docker ps -f name=$(PROJECT_NAME) -aq`; do \
-		serviceName=`docker inspect --format '{{index .Config.Labels "com.docker.compose.service" }}' $$containerId`; \
-		if [ ! -z $$serviceName ] && echo $(GUI_SERVICES) | grep -w $$serviceName > /dev/null; then \
-			xhost +local:`docker inspect --format='{{ .Config.Hostname }}' $$containerId`; \
-		fi; \
-	done
+	@if ! command -v xhost &> /dev/null; then \
+		echo -e "\033[1;33;40mWarning: xhost command not found. GUIs will not be available.\033[0m"; \
+	else \
+		for containerId in `docker ps -f name=$(PROJECT_NAME) -aq`; do \
+			serviceName=`docker inspect --format '{{index .Config.Labels "com.docker.compose.service" }}' $$containerId`; \
+			if [ ! -z $$serviceName ] && echo $(GUI_SERVICES) | grep -w $$serviceName > /dev/null; then \
+				xhost +local:`docker inspect --format='{{ .Config.Hostname }}' $$containerId`; \
+			fi; \
+		done; \
+	fi
+
 
 # shutdown any and all services (stop and remove containers)
 .PHONY: down
